//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subscription.Business
{
    
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.CompanyLocations = new HashSet<CompanyLocation>();
            this.Contacts = new HashSet<Contact>();
            this.Person_Address = new HashSet<Person_Address>();
        }
    
        
            
             public Nullable<long> IdAddress { get; set; }
                    public string AddressLine1 { get; set; }
                    public string AddressLine2 { get; set; }
                    public string AddressLine3 { get; set; }
                    public string AddressLine4 { get; set; }
                    public string Postcode { get; set; }
                    public Nullable<long> IdCity { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdCountry { get; set; }
                    public string City { get; set; }
        
        public virtual ICollection<CompanyLocation> CompanyLocations { get; set; }
        public virtual City City1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Person_Address> Person_Address { get; set; }
    }
    public partial class ApprovalMessage
    {
        
            
             public Nullable<long> IdApprovalMessage { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdWorkflowToInitiate { get; set; }
                    public Nullable<long> IdWorkflowAction { get; set; }
                    public Nullable<bool> IsRequestRequired { get; set; }
                    public Nullable<bool> IsPostApprovalRequired { get; set; }
                    public Nullable<bool> IsProgressBlocked { get; set; }
        
        public virtual WorkflowAction WorkflowAction { get; set; }
        public virtual Workflow Workflow { get; set; }
    }
    public partial class Bank
    {
        public Bank()
        {
            this.BankStatementStagings = new HashSet<BankStatementStaging>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        
            
             public Nullable<long> IdBank { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdBankTransferPaymentMethod { get; set; }
                    public Nullable<long> IdTransactionAccount { get; set; }
                    public Nullable<long> IdTransactionTemplate { get; set; }
        
        public virtual ICollection<BankStatementStaging> BankStatementStagings { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual TransactionAccount TransactionAccount { get; set; }
        public virtual TransactionTemplate TransactionTemplate { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
    public partial class BankReconHitType
    {
        public BankReconHitType()
        {
            this.BankStatementStagingHits = new HashSet<BankStatementStagingHit>();
        }
    
        
            
             public Nullable<long> IdBankReconHitType { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<BankStatementStagingHit> BankStatementStagingHits { get; set; }
    }
    public partial class BankReconOrderProcessState
    {
        public BankReconOrderProcessState()
        {
            this.BankStatementStagings = new HashSet<BankStatementStaging>();
        }
    
        
            
             public Nullable<long> IdBankReconOrderProcessState { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<BankStatementStaging> BankStatementStagings { get; set; }
    }
    public partial class BankReconOrderType
    {
        public BankReconOrderType()
        {
            this.BankStatementStagingDetails = new HashSet<BankStatementStagingDetail>();
        }
    
        
            
             public Nullable<long> IdBankReconOrderType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<BankStatementStagingDetail> BankStatementStagingDetails { get; set; }
    }
    public partial class BankStatementHitList
    {
        public BankStatementHitList()
        {
            this.BankStatementHitList_TransactionPreset = new HashSet<BankStatementHitList_TransactionPreset>();
            this.BankStatementStagingHits = new HashSet<BankStatementStagingHit>();
            this.TemporaryTransactions = new HashSet<TemporaryTransaction>();
        }
    
        
            
             public Nullable<long> IdBankStatementHitList { get; set; }
                    public string Description { get; set; }
                    public Nullable<double> Amount { get; set; }
                    public Nullable<int> HitCount { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdBankStatementStagingDetail { get; set; }
        
        public virtual BankStatementStagingDetail BankStatementStagingDetail { get; set; }
        public virtual ICollection<BankStatementHitList_TransactionPreset> BankStatementHitList_TransactionPreset { get; set; }
        public virtual ICollection<BankStatementStagingHit> BankStatementStagingHits { get; set; }
        public virtual ICollection<TemporaryTransaction> TemporaryTransactions { get; set; }
    }
    public partial class BankStatementHitList_TransactionPreset
    {
        
            
             public Nullable<long> IdBankStatementHitList_TransactionPreset { get; set; }
                    public Nullable<long> IdBankStatementHitList { get; set; }
                    public Nullable<long> IdTransactionPreset { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual BankStatementHitList BankStatementHitList { get; set; }
        public virtual TransactionPreset TransactionPreset { get; set; }
    }
    public partial class BankStatementStaging
    {
        public BankStatementStaging()
        {
            this.BankStatementStagingDetails = new HashSet<BankStatementStagingDetail>();
        }
    
        
            
             public Nullable<long> IdBankStatementStaging { get; set; }
                    public Nullable<System.DateTime> UploadDate { get; set; }
                    public Nullable<long> IdUserUploadedBy { get; set; }
                    public string Account { get; set; }
                    public Nullable<System.DateTime> BankStatementDateFrom { get; set; }
                    public Nullable<System.DateTime> BankStatementDateTo { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdDocument { get; set; }
                    public Nullable<long> IdBankStatementStagingState { get; set; }
                    public Nullable<long> IdBank { get; set; }
                    public Nullable<long> IdBankReconOrderProcessState { get; set; }
        
        public virtual BankReconOrderProcessState BankReconOrderProcessState { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual BankStatementStagingState BankStatementStagingState { get; set; }
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<BankStatementStagingDetail> BankStatementStagingDetails { get; set; }
    }
    public partial class BankStatementStagingDetail
    {
        public BankStatementStagingDetail()
        {
            this.BankStatementHitLists = new HashSet<BankStatementHitList>();
            this.BankStatementStagingHits = new HashSet<BankStatementStagingHit>();
            this.TemporaryTransactions = new HashSet<TemporaryTransaction>();
            this.Transaction_BankStatementStagingDetail = new HashSet<Transaction_BankStatementStagingDetail>();
        }
    
        
            
             public Nullable<long> IdBankStatementStagingDetail { get; set; }
                    public Nullable<long> IdBankStatementStaging { get; set; }
                    public Nullable<int> StatementLineNo { get; set; }
                    public Nullable<System.DateTime> ValueDate { get; set; }
                    public string BranchCode { get; set; }
                    public string Remarks { get; set; }
                    public Nullable<double> DebitAmount { get; set; }
                    public Nullable<double> CreditAmount { get; set; }
                    public Nullable<double> Balance { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdBankStatementStagingDetailBatch { get; set; }
                    public Nullable<long> IdBankReconOrderType { get; set; }
                    public string OrderNumber { get; set; }
        
        public virtual BankReconOrderType BankReconOrderType { get; set; }
        public virtual ICollection<BankStatementHitList> BankStatementHitLists { get; set; }
        public virtual BankStatementStaging BankStatementStaging { get; set; }
        public virtual BankStatementStagingDetailBatch BankStatementStagingDetailBatch { get; set; }
        public virtual ICollection<BankStatementStagingHit> BankStatementStagingHits { get; set; }
        public virtual ICollection<TemporaryTransaction> TemporaryTransactions { get; set; }
        public virtual ICollection<Transaction_BankStatementStagingDetail> Transaction_BankStatementStagingDetail { get; set; }
    }
    public partial class BankStatementStagingDetailBatch
    {
        public BankStatementStagingDetailBatch()
        {
            this.BankStatementStagingDetails = new HashSet<BankStatementStagingDetail>();
        }
    
        
            
             public Nullable<long> IdBankStatementStagingDetailBatch { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdBankStatementStagingState { get; set; }
                    public Nullable<int> BatchNumber { get; set; }
        
        public virtual ICollection<BankStatementStagingDetail> BankStatementStagingDetails { get; set; }
        public virtual BankStatementStagingState BankStatementStagingState { get; set; }
    }
    public partial class BankStatementStagingHit
    {
        public BankStatementStagingHit()
        {
            this.BankStatementStagingHit_TransactionPreset = new HashSet<BankStatementStagingHit_TransactionPreset>();
            this.TemporaryTransactions = new HashSet<TemporaryTransaction>();
        }
    
        
            
             public Nullable<long> IdBankStatementStagingHit { get; set; }
                    public Nullable<long> IdBankStatementStagingDetail { get; set; }
                    public Nullable<int> HitCount { get; set; }
                    public Nullable<long> IdBankReconHitType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdBankStatementHitList { get; set; }
                    public Nullable<long> IdOrder { get; set; }
        
        public virtual BankStatementHitList BankStatementHitList { get; set; }
        public virtual BankStatementStagingDetail BankStatementStagingDetail { get; set; }
        public virtual BankReconHitType BankReconHitType { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<BankStatementStagingHit_TransactionPreset> BankStatementStagingHit_TransactionPreset { get; set; }
        public virtual ICollection<TemporaryTransaction> TemporaryTransactions { get; set; }
    }
    public partial class BankStatementStagingHit_TransactionPreset
    {
        
            
             public Nullable<long> IdBankStatementStagingHit_TransactionPreset { get; set; }
                    public Nullable<long> IdBankStatementStagingHit { get; set; }
                    public Nullable<long> IdTransactionPreset { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual BankStatementStagingHit BankStatementStagingHit { get; set; }
        public virtual TransactionPreset TransactionPreset { get; set; }
    }
    public partial class BankStatementStagingState
    {
        public BankStatementStagingState()
        {
            this.BankStatementStagings = new HashSet<BankStatementStaging>();
            this.BankStatementStagingDetailBatches = new HashSet<BankStatementStagingDetailBatch>();
        }
    
        
            
             public Nullable<long> IdBankStatementStagingState { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<BankStatementStaging> BankStatementStagings { get; set; }
        public virtual ICollection<BankStatementStagingDetailBatch> BankStatementStagingDetailBatches { get; set; }
    }
    public partial class City
    {
        public City()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        
            
             public Nullable<long> IdCity { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdCountry { get; set; }
        
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Country Country { get; set; }
    }
    public partial class Company
    {
        public Company()
        {
            this.Company_ContactType = new HashSet<Company_ContactType>();
            this.Customers = new HashSet<Customer>();
            this.CompanyLocations = new HashSet<CompanyLocation>();
            this.Concepts = new HashSet<Concept>();
        }
    
        
            
             public Nullable<long> IdCompany { get; set; }
                    public string Name { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
                    public Nullable<System.DateTime> EstablishmentDate { get; set; }
                    public Nullable<long> IdEmployeeNoRange { get; set; }
                    public Nullable<long> IdParentCompany { get; set; }
                    public string RegistrationCode { get; set; }
                    public string VatRegistrationNo { get; set; }
                    public Nullable<long> IdCompanyLogo { get; set; }
                    public Nullable<long> IdHostedDomain { get; set; }
                    public Nullable<long> IdOpeningHourType { get; set; }
                    public Nullable<long> IdConcept { get; set; }
        
        public virtual ICollection<Company_ContactType> Company_ContactType { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Concept Concept { get; set; }
        public virtual Document Document { get; set; }
        public virtual ICollection<CompanyLocation> CompanyLocations { get; set; }
        public virtual ICollection<Concept> Concepts { get; set; }
    }
    public partial class Company_ContactType
    {
        
            
             public Nullable<long> IdCompany_ContactType { get; set; }
                    public Nullable<long> IdCompany { get; set; }
                    public Nullable<long> IdContactType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual Company Company { get; set; }
        public virtual ContactType ContactType { get; set; }
    }
    public partial class CompanyLocation
    {
        
            
             public Nullable<long> IdCompanyLocation { get; set; }
                    public Nullable<long> IdCompany { get; set; }
                    public Nullable<long> IdAddress { get; set; }
                    public string Detail { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string ColorCode { get; set; }
        
        public virtual Company Company { get; set; }
        public virtual Address Address { get; set; }
    }
    public partial class Concept
    {
        public Concept()
        {
            this.Companies = new HashSet<Company>();
            this.Concept_Address = new HashSet<Concept_Address>();
            this.Concept_ContactType = new HashSet<Concept_ContactType>();
            this.Customers = new HashSet<Customer>();
        }
    
        
            
             public Nullable<long> IdConcept { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdConceptType { get; set; }
                    public Nullable<long> IdCompany { get; set; }
                    public Nullable<long> IdPerson { get; set; }
        
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Concept_Address> Concept_Address { get; set; }
        public virtual ICollection<Concept_ContactType> Concept_ContactType { get; set; }
        public virtual Concept Concept1 { get; set; }
        public virtual Concept Concept2 { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
    public partial class Concept_Address
    {
        
            
             public Nullable<long> IdConcept_Address { get; set; }
                    public Nullable<long> IdConcept { get; set; }
                    public Nullable<long> IdAddress { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Concept Concept { get; set; }
    }
    public partial class Concept_ContactType
    {
        
            
             public Nullable<long> IdConcept_ContactType { get; set; }
                    public Nullable<long> IdConcept { get; set; }
                    public Nullable<long> IdContactType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ContactType ContactType { get; set; }
        public virtual Concept Concept { get; set; }
    }
    public partial class Contact
    {
        
            
             public Nullable<long> IdContact { get; set; }
                    public string Firstname { get; set; }
                    public string Lastname { get; set; }
                    public string Phone { get; set; }
                    public string Fax { get; set; }
                    public string Email { get; set; }
                    public Nullable<long> IdAddress { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Address Address { get; set; }
    }
    public partial class ContactType
    {
        public ContactType()
        {
            this.Company_ContactType = new HashSet<Company_ContactType>();
            this.Concept_ContactType = new HashSet<Concept_ContactType>();
            this.ContactType1 = new HashSet<ContactType>();
            this.OrderConcept_ContactType = new HashSet<OrderConcept_ContactType>();
            this.Person_ContactType = new HashSet<Person_ContactType>();
        }
    
        
            
             public Nullable<long> IdContactType { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdParentContactType { get; set; }
                    public Nullable<int> DisplayOrder { get; set; }
                    public string IconClass { get; set; }
                    public string Action { get; set; }
        
        public virtual ICollection<Company_ContactType> Company_ContactType { get; set; }
        public virtual ICollection<Concept_ContactType> Concept_ContactType { get; set; }
        public virtual ICollection<ContactType> ContactType1 { get; set; }
        public virtual ContactType ContactType2 { get; set; }
        public virtual ICollection<OrderConcept_ContactType> OrderConcept_ContactType { get; set; }
        public virtual ICollection<Person_ContactType> Person_ContactType { get; set; }
    }
    public partial class Country
    {
        public Country()
        {
            this.Addresses = new HashSet<Address>();
            this.Cities = new HashSet<City>();
        }
    
        
            
             public Nullable<long> IdCountry { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<City> Cities { get; set; }
    }
    public partial class Customer
    {
        public Customer()
        {
            this.TransactionPresets = new HashSet<TransactionPreset>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        
            
             public Nullable<long> IdCustomer { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string FullName { get; set; }
                    public Nullable<long> IdConcept { get; set; }
                    public Nullable<long> IdPerson { get; set; }
                    public Nullable<long> IdCompany { get; set; }
                    public Nullable<long> IdCustomerType { get; set; }
                    public string AccountNumber { get; set; }
        
        public virtual ICollection<TransactionPreset> TransactionPresets { get; set; }
        public virtual Company Company { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual Concept Concept { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
    public partial class CustomerType
    {
        public CustomerType()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        
            
             public Nullable<long> IdCustomerType { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<Customer> Customers { get; set; }
    }
    public partial class Document
    {
        public Document()
        {
            this.BankStatementStagings = new HashSet<BankStatementStaging>();
            this.Companies = new HashSet<Company>();
            this.TemporaryTransactionOrders = new HashSet<TemporaryTransactionOrder>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        
            
             public Nullable<long> IdDocument { get; set; }
                    public string FileName { get; set; }
                    public string FileExtension { get; set; }
                    public string PhysicalFilePath { get; set; }
                    public Nullable<long> DocumentOrder { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdDocumentType { get; set; }
                    public Nullable<long> IdParameterBasePhysicalFilePath { get; set; }
                    public Nullable<long> IdParameterBaseServerUrl { get; set; }
                    public string ServerFilePath { get; set; }
        
        public virtual ICollection<BankStatementStaging> BankStatementStagings { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Parameter Parameter { get; set; }
        public virtual Parameter Parameter1 { get; set; }
        public virtual ICollection<TemporaryTransactionOrder> TemporaryTransactionOrders { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.Documents = new HashSet<Document>();
        }
    
        
            
             public Nullable<long> IdDocumentType { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<Document> Documents { get; set; }
    }
    public partial class EndType
    {
        
            
             public Nullable<long> IdEndType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        }
    public partial class Frequency
    {
        public Frequency()
        {
            this.ScheduleSettings = new HashSet<ScheduleSetting>();
        }
    
        
            
             public Nullable<long> IdFrequency { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<ScheduleSetting> ScheduleSettings { get; set; }
    }
    public partial class MailRecipient
    {
        
            
             public Nullable<long> IdMailRecipient { get; set; }
                    public string Name { get; set; }
                    public string EmailAddress { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdMailToSend { get; set; }
                    public Nullable<long> IdMailStatus { get; set; }
                    public Nullable<long> IdMailRecipientType { get; set; }
        
        public virtual MailRecipientType MailRecipientType { get; set; }
        public virtual MailStatu MailStatu { get; set; }
        public virtual MailToSend MailToSend { get; set; }
    }
    public partial class MailRecipientType
    {
        public MailRecipientType()
        {
            this.MailRecipients = new HashSet<MailRecipient>();
        }
    
        
            
             public Nullable<long> IdMailRecipientType { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<MailRecipient> MailRecipients { get; set; }
    }
    public partial class MailServerSetting
    {
        public MailServerSetting()
        {
            this.MailToSends = new HashSet<MailToSend>();
        }
    
        
            
             public Nullable<long> IdMailServerSetting { get; set; }
                    public Nullable<bool> UseSSL { get; set; }
                    public Nullable<int> ClientPort { get; set; }
                    public string Host { get; set; }
                    public string Username { get; set; }
                    public string Password { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<int> Priority { get; set; }
                    public string DefaultName { get; set; }
        
        public virtual ICollection<MailToSend> MailToSends { get; set; }
    }
    public partial class MailStatu
    {
        public MailStatu()
        {
            this.MailRecipients = new HashSet<MailRecipient>();
            this.MailToSends = new HashSet<MailToSend>();
        }
    
        
            
             public Nullable<long> IdMailStatus { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<MailRecipient> MailRecipients { get; set; }
        public virtual ICollection<MailToSend> MailToSends { get; set; }
    }
    public partial class MailToSend
    {
        public MailToSend()
        {
            this.MailRecipients = new HashSet<MailRecipient>();
            this.MailToSendDocuments = new HashSet<MailToSendDocument>();
            this.Transaction_MailToSend = new HashSet<Transaction_MailToSend>();
        }
    
        
            
             public Nullable<long> IdMailToSend { get; set; }
                    public Nullable<long> IdMailServerSetting { get; set; }
                    public Nullable<long> IdEmailStatus { get; set; }
                    public Nullable<int> FailureCount { get; set; }
                    public string EmailSubject { get; set; }
                    public string ErrorMessage { get; set; }
                    public string EmailBody { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<MailRecipient> MailRecipients { get; set; }
        public virtual MailServerSetting MailServerSetting { get; set; }
        public virtual MailStatu MailStatu { get; set; }
        public virtual ICollection<MailToSendDocument> MailToSendDocuments { get; set; }
        public virtual ICollection<Transaction_MailToSend> Transaction_MailToSend { get; set; }
    }
    public partial class MailToSendDocument
    {
        
            
             public Nullable<long> IdMailToSendDocument { get; set; }
                    public Nullable<long> IdMailToSend { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string RelativeDocumentPath { get; set; }
                    public string DocumentName { get; set; }
        
        public virtual MailToSend MailToSend { get; set; }
    }
    public partial class NLogDetail
    {
        
            
             public Nullable<long> IdNLogDetail { get; set; }
                    public string CallSite { get; set; }
                    public string Application { get; set; }
                    public Nullable<System.DateTime> Logged { get; set; }
                    public string Level { get; set; }
                    public string Message { get; set; }
                    public string UserName { get; set; }
                    public string ServerName { get; set; }
                    public string Port { get; set; }
                    public string Url { get; set; }
                    public string Https { get; set; }
                    public string ServerAddress { get; set; }
                    public string RemoteAddress { get; set; }
                    public string Logger { get; set; }
                    public string Exception { get; set; }
                    public string Stacktrace { get; set; }
                    public Nullable<System.DateTime> Date { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        }
    public partial class Order
    {
        public Order()
        {
            this.BankStatementStagingHits = new HashSet<BankStatementStagingHit>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        
            
             public Nullable<long> IdOrder { get; set; }
                    public Nullable<System.DateTime> OrderDate { get; set; }
                    public Nullable<long> IdOrderConcept { get; set; }
                    public Nullable<long> IdUserAuthor { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string OrderNumber { get; set; }
                    public Nullable<long> IdOrderSource { get; set; }
                    public Nullable<long> IdOrderState { get; set; }
                    public Nullable<double> TotalAmount { get; set; }
        
        public virtual ICollection<BankStatementStagingHit> BankStatementStagingHits { get; set; }
        public virtual User User { get; set; }
        public virtual OrderConcept OrderConcept { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
    public partial class OrderAddress
    {
        public OrderAddress()
        {
            this.OrderConcept_OrderAddress = new HashSet<OrderConcept_OrderAddress>();
        }
    
        
            
             public Nullable<long> IdOrderAddress { get; set; }
                    public string AddressLine1 { get; set; }
                    public string AddressLine2 { get; set; }
                    public string AddressLine3 { get; set; }
                    public string AddressLine4 { get; set; }
                    public string Postcode { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<double> Lat { get; set; }
                    public Nullable<double> Lng { get; set; }
                    public string City { get; set; }
        
        public virtual ICollection<OrderConcept_OrderAddress> OrderConcept_OrderAddress { get; set; }
    }
    public partial class OrderCompany
    {
        public OrderCompany()
        {
            this.OrderConcepts = new HashSet<OrderConcept>();
        }
    
        
            
             public Nullable<long> IdOrderCompany { get; set; }
                    public string Name { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<OrderConcept> OrderConcepts { get; set; }
    }
    public partial class OrderConcept
    {
        public OrderConcept()
        {
            this.Orders = new HashSet<Order>();
            this.OrderConcept_ContactType = new HashSet<OrderConcept_ContactType>();
            this.OrderConcept_OrderAddress = new HashSet<OrderConcept_OrderAddress>();
        }
    
        
            
             public Nullable<long> IdOrderConcept { get; set; }
                    public Nullable<long> IdOrderCompany { get; set; }
                    public Nullable<long> IdOrderPerson { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<Order> Orders { get; set; }
        public virtual OrderCompany OrderCompany { get; set; }
        public virtual ICollection<OrderConcept_ContactType> OrderConcept_ContactType { get; set; }
        public virtual OrderPerson OrderPerson { get; set; }
        public virtual ICollection<OrderConcept_OrderAddress> OrderConcept_OrderAddress { get; set; }
    }
    public partial class OrderConcept_ContactType
    {
        
            
             public Nullable<long> IdOrderConcept_ContactType { get; set; }
                    public Nullable<long> IdOrderConcept { get; set; }
                    public Nullable<long> IdContactType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ContactType ContactType { get; set; }
        public virtual OrderConcept OrderConcept { get; set; }
    }
    public partial class OrderConcept_OrderAddress
    {
        
            
             public Nullable<long> IdOrderConcept_OrderAddress { get; set; }
                    public Nullable<long> IdOrderConcept { get; set; }
                    public Nullable<long> IdOrderAddress { get; set; }
                    public string Detail { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual OrderAddress OrderAddress { get; set; }
        public virtual OrderConcept OrderConcept { get; set; }
    }
    public partial class OrderDetail
    {
        
            
             public Nullable<long> IdOrderDetail { get; set; }
                    public Nullable<long> IdOrder { get; set; }
                    public Nullable<long> IdProduct { get; set; }
                    public Nullable<double> Quantity { get; set; }
                    public Nullable<double> Rate { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
    public partial class OrderPerson
    {
        public OrderPerson()
        {
            this.OrderConcepts = new HashSet<OrderConcept>();
        }
    
        
            
             public Nullable<long> IdOrderPerson { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Firstname { get; set; }
                    public string Lastname { get; set; }
                    public string Othername { get; set; }
                    public Nullable<long> IdProfilePic { get; set; }
                    public string Headline { get; set; }
                    public string ShortBiography { get; set; }
                    public Nullable<System.DateTime> Dob { get; set; }
                    public Nullable<long> IdNationality { get; set; }
                    public Nullable<bool> HasDrivingLicense { get; set; }
                    public Nullable<long> IdCoverPic { get; set; }
                    public Nullable<long> IdHostedDomain { get; set; }
                    public Nullable<long> IdTitle { get; set; }
                    public string NationalIdentificationNumber { get; set; }
        
        public virtual Title Title { get; set; }
        public virtual ICollection<OrderConcept> OrderConcepts { get; set; }
    }
    public partial class OrderState
    {
        public OrderState()
        {
            this.Orders = new HashSet<Order>();
        }
    
        
            
             public Nullable<long> IdOrderState { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<Order> Orders { get; set; }
    }
    public partial class Parameter
    {
        public Parameter()
        {
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
        }
    
        
            
             public Nullable<long> IdParameter { get; set; }
                    public string ParamaterValue { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> Code { get; set; }
        
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Document> Documents1 { get; set; }
    }
    public partial class Payment
    {
        public Payment()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.Transactions = new HashSet<Transaction>();
            this.Transaction_Payment = new HashSet<Transaction_Payment>();
        }
    
        
            
             public Nullable<long> IdPayment { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<System.DateTime> PaymentDate { get; set; }
                    public Nullable<long> IdUserAuthor { get; set; }
                    public Nullable<long> IdTransaction { get; set; }
        
        public virtual User User { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Transaction_Payment> Transaction_Payment { get; set; }
    }
    public partial class PaymentDetail
    {
        
            
             public Nullable<long> IdPaymentDetail { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<double> PaymentAmount { get; set; }
                    public Nullable<long> IdPaymentMethod { get; set; }
                    public Nullable<long> IdPayment { get; set; }
                    public string ChequeNo { get; set; }
                    public string Description { get; set; }
                    public string BankAccountNo { get; set; }
                    public Nullable<long> IdBank { get; set; }
        
        public virtual Bank Bank { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Payment Payment { get; set; }
    }
    public partial class PaymentDueState
    {
        
            
             public Nullable<long> IdPaymentDueState { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        }
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.Banks = new HashSet<Bank>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        
            
             public Nullable<long> IdPaymentMethod { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<Bank> Banks { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
    public partial class Permission
    {
        public Permission()
        {
            this.Role_Permission = new HashSet<Role_Permission>();
            this.User_Permission = new HashSet<User_Permission>();
        }
    
        
            
             public Nullable<long> IdPermission { get; set; }
                    public string PermissionName { get; set; }
                    public Nullable<long> PermissionCode { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<Role_Permission> Role_Permission { get; set; }
        public virtual ICollection<User_Permission> User_Permission { get; set; }
    }
    public partial class Person
    {
        public Person()
        {
            this.Users = new HashSet<User>();
            this.Concepts = new HashSet<Concept>();
            this.Customers = new HashSet<Customer>();
            this.Person_Address = new HashSet<Person_Address>();
            this.Person_ContactType = new HashSet<Person_ContactType>();
        }
    
        
            
             public Nullable<long> IdPerson { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Firstname { get; set; }
                    public string Lastname { get; set; }
                    public Nullable<System.DateTime> Dob { get; set; }
                    public Nullable<long> IdNationality { get; set; }
                    public Nullable<long> IdTitle { get; set; }
                    public string NationalIdentificationNumber { get; set; }
        
        public virtual ICollection<User> Users { get; set; }
        public virtual Title Title { get; set; }
        public virtual ICollection<Concept> Concepts { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Person_Address> Person_Address { get; set; }
        public virtual ICollection<Person_ContactType> Person_ContactType { get; set; }
    }
    public partial class Person_Address
    {
        
            
             public Nullable<long> IdPerson_Address { get; set; }
                    public Nullable<long> IdPerson { get; set; }
                    public Nullable<long> IdAddress { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Address Address { get; set; }
        public virtual Person Person { get; set; }
    }
    public partial class Person_ContactType
    {
        
            
             public Nullable<long> IdPerson_ContactType { get; set; }
                    public Nullable<long> IdPerson { get; set; }
                    public Nullable<long> IdContactType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsPrimary { get; set; }
        
        public virtual ContactType ContactType { get; set; }
        public virtual Person Person { get; set; }
    }
    public partial class Product
    {
        public Product()
        {
            this.TransactionDetailPresets = new HashSet<TransactionDetailPreset>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Product1 = new HashSet<Product>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        
            
             public Nullable<long> IdProduct { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
                    public Nullable<long> IdProductType { get; set; }
                    public string ItemCode { get; set; }
                    public Nullable<double> Rate { get; set; }
                    public Nullable<long> IdTransactionAccount { get; set; }
                    public string Name { get; set; }
                    public Nullable<long> IdDocument { get; set; }
                    public Nullable<bool> IsLimitedByStock { get; set; }
                    public Nullable<long> IdParentProduct { get; set; }
                    public string ImgUrl { get; set; }
                    public Nullable<bool> IsAvailableOnOrder { get; set; }
        
        public virtual ICollection<TransactionDetailPreset> TransactionDetailPresets { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Product> Product1 { get; set; }
        public virtual Product Product2 { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
    public partial class ProductType
    {
        public ProductType()
        {
            this.Products = new HashSet<Product>();
        }
    
        
            
             public Nullable<long> IdProductType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<Product> Products { get; set; }
    }
    public partial class Receipt
    {
        
            
             public Nullable<long> IdReceipt { get; set; }
                    public Nullable<double> Number { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdUser { get; set; }
        
        public virtual User User { get; set; }
    }
    public partial class Request
    {
        public Request()
        {
            this.RequestMessageQueues = new HashSet<RequestMessageQueue>();
        }
    
        
            
             public Nullable<long> IdRequest { get; set; }
                    public Nullable<long> IdRequestType { get; set; }
                    public Nullable<long> IdRequestAuthor { get; set; }
                    public Nullable<System.DateTime> RequestDate { get; set; }
                    public Nullable<long> IdWorkflowState { get; set; }
                    public Nullable<long> IdUserAssignedTo { get; set; }
                    public string Remarks { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string JsonContent { get; set; }
        
        public virtual RequestType RequestType { get; set; }
        public virtual WorkflowState WorkflowState { get; set; }
        public virtual ICollection<RequestMessageQueue> RequestMessageQueues { get; set; }
    }
    public partial class RequestMessageQueue
    {
        
            
             public Nullable<long> IdRequestMessageQueue { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Message { get; set; }
                    public Nullable<long> IdRequest { get; set; }
                    public Nullable<long> IdUserReceiver { get; set; }
                    public Nullable<System.DateTime> DateCreated { get; set; }
        
        public virtual Request Request { get; set; }
    }
    public partial class RequestType
    {
        public RequestType()
        {
            this.Requests = new HashSet<Request>();
            this.RequestType_User = new HashSet<RequestType_User>();
        }
    
        
            
             public Nullable<long> IdRequestType { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdWorkflow { get; set; }
        
        public virtual ICollection<Request> Requests { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<RequestType_User> RequestType_User { get; set; }
    }
    public partial class RequestType_User
    {
        public RequestType_User()
        {
            this.RequestType_User1 = new HashSet<RequestType_User>();
        }
    
        
            
             public Nullable<long> IdRequestType_User { get; set; }
                    public Nullable<long> IdRequestType { get; set; }
                    public Nullable<long> IdUser { get; set; }
                    public Nullable<long> IdParentRequestType_User { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<int> Priority { get; set; }
        
        public virtual User User { get; set; }
        public virtual RequestType RequestType { get; set; }
        public virtual ICollection<RequestType_User> RequestType_User1 { get; set; }
        public virtual RequestType_User RequestType_User2 { get; set; }
    }
    public partial class Role
    {
        public Role()
        {
            this.Role_Permission = new HashSet<Role_Permission>();
            this.User_Role = new HashSet<User_Role>();
        }
    
        
            
             public Nullable<long> IdRole { get; set; }
                    public string Name { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<Role_Permission> Role_Permission { get; set; }
        public virtual ICollection<User_Role> User_Role { get; set; }
    }
    public partial class Role_Permission
    {
        
            
             public Nullable<long> IdRole_Permission { get; set; }
                    public Nullable<long> IdRole { get; set; }
                    public Nullable<long> IdPermission { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Permission Permission { get; set; }
        public virtual Role Role { get; set; }
    }
    public partial class ScheduleSetting
    {
        
            
             public Nullable<long> IdScheduleSetting { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdFrequency { get; set; }
                    public string ReccurEvery { get; set; }
                    public string WeekOccursOnDays { get; set; }
                    public string MonthOccurs { get; set; }
                    public string MonthOnSpecificDays { get; set; }
                    public string MonthEveryOrdinal { get; set; }
                    public string MonthEveryDays { get; set; }
                    public Nullable<System.DateTime> StartDate { get; set; }
                    public Nullable<System.DateTime> EndDate { get; set; }
                    public Nullable<long> IdTransaction { get; set; }
        
        public virtual Frequency Frequency { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
    public partial class StockLocation
    {
        
            
             public Nullable<long> IdStockLocation { get; set; }
                    public string Description { get; set; }
                    public Nullable<int> DisplayOrder { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        }
    public partial class TemporaryPayment
    {
        public TemporaryPayment()
        {
            this.TemporaryPaymentDetails = new HashSet<TemporaryPaymentDetail>();
            this.TemporaryTransactions = new HashSet<TemporaryTransaction>();
        }
    
        
            
             public Nullable<long> IdTemporaryPayment { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<System.DateTime> PaymentDate { get; set; }
                    public Nullable<long> IdUserAuthor { get; set; }
                    public string Identifier { get; set; }
        
        public virtual ICollection<TemporaryPaymentDetail> TemporaryPaymentDetails { get; set; }
        public virtual ICollection<TemporaryTransaction> TemporaryTransactions { get; set; }
    }
    public partial class TemporaryPaymentDetail
    {
        
            
             public Nullable<long> IdTemporaryPaymentDetail { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<double> PaymentAmount { get; set; }
                    public Nullable<long> IdPaymentMethod { get; set; }
                    public Nullable<long> IdTemporaryPayment { get; set; }
                    public string ChequeNo { get; set; }
                    public string Identifier { get; set; }
        
        public virtual TemporaryPayment TemporaryPayment { get; set; }
    }
    public partial class TemporaryTransaction
    {
        public TemporaryTransaction()
        {
            this.TemporaryTransactionDetails = new HashSet<TemporaryTransactionDetail>();
        }
    
        
            
             public Nullable<long> IdTemporaryTransaction { get; set; }
                    public Nullable<long> IdTransactionType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<System.DateTime> TransactionDate { get; set; }
                    public string ReceiptNo { get; set; }
                    public Nullable<long> IdCustomer { get; set; }
                    public Nullable<long> IdTransactionClass { get; set; }
                    public Nullable<long> IdTransactionTemplate { get; set; }
                    public Nullable<long> IdTransactionAccount { get; set; }
                    public string Memo { get; set; }
                    public Nullable<System.DateTime> CapturedDate { get; set; }
                    public Nullable<double> TotalAmount { get; set; }
                    public Nullable<long> IdUserAuthor { get; set; }
                    public Nullable<long> IdTemporaryPayment { get; set; }
                    public Nullable<long> IdBankStatementStagingDetail { get; set; }
                    public string Identitifier { get; set; }
                    public Nullable<long> IdBankStatementHitList { get; set; }
                    public Nullable<long> IdBankStatementStagingHit { get; set; }
        
        public virtual BankStatementHitList BankStatementHitList { get; set; }
        public virtual BankStatementStagingDetail BankStatementStagingDetail { get; set; }
        public virtual BankStatementStagingHit BankStatementStagingHit { get; set; }
        public virtual TemporaryPayment TemporaryPayment { get; set; }
        public virtual ICollection<TemporaryTransactionDetail> TemporaryTransactionDetails { get; set; }
    }
    public partial class TemporaryTransactionDetail
    {
        
            
             public Nullable<long> IdTemporaryTransactionDetail { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdTemporaryTransaction { get; set; }
                    public Nullable<long> IdProduct { get; set; }
                    public string Description { get; set; }
                    public Nullable<double> Quantity { get; set; }
                    public Nullable<double> Rate { get; set; }
                    public Nullable<long> IdTransactionClass { get; set; }
                    public string Identifier { get; set; }
        
        public virtual TemporaryTransaction TemporaryTransaction { get; set; }
    }
    public partial class TemporaryTransactionOrder
    {
        
            
             public Nullable<long> IdTemporaryTransactionOrder { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdTemporaryTransactionOrderState { get; set; }
                    public string TransactionJson { get; set; }
                    public string SignatureImage { get; set; }
                    public Nullable<System.DateTime> TemporaryTransactionOrderDate { get; set; }
                    public string IdWorkstation { get; set; }
                    public Nullable<long> IdSignatureDocument { get; set; }
        
        public virtual TemporaryTransactionOrderState TemporaryTransactionOrderState { get; set; }
        public virtual Document Document { get; set; }
    }
    public partial class TemporaryTransactionOrderState
    {
        public TemporaryTransactionOrderState()
        {
            this.TemporaryTransactionOrders = new HashSet<TemporaryTransactionOrder>();
        }
    
        
            
             public Nullable<long> IdTemporaryTransactionOrderState { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<TemporaryTransactionOrder> TemporaryTransactionOrders { get; set; }
    }
    public partial class Title
    {
        public Title()
        {
            this.OrderPersons = new HashSet<OrderPerson>();
            this.People = new HashSet<Person>();
        }
    
        
            
             public Nullable<long> IdTitle { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<OrderPerson> OrderPersons { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
    public partial class Transaction
    {
        public Transaction()
        {
            this.ScheduleSettings = new HashSet<ScheduleSetting>();
            this.TransactionDues = new HashSet<TransactionDue>();
            this.TransactionDue_Transaction = new HashSet<TransactionDue_Transaction>();
            this.Payments = new HashSet<Payment>();
            this.Transaction_Payment = new HashSet<Transaction_Payment>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
            this.Transaction_MailToSend = new HashSet<Transaction_MailToSend>();
            this.Transaction_BankStatementStagingDetail = new HashSet<Transaction_BankStatementStagingDetail>();
        }
    
        
            
             public Nullable<long> IdTransaction { get; set; }
                    public Nullable<long> IdTransactionType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<System.DateTime> TransactionDate { get; set; }
                    public string ReceiptNo { get; set; }
                    public Nullable<long> IdCustomer { get; set; }
                    public Nullable<long> IdTransactionClass { get; set; }
                    public Nullable<long> IdTransactionTemplate { get; set; }
                    public Nullable<long> IdTransactionAccount { get; set; }
                    public string Memo { get; set; }
                    public Nullable<System.DateTime> CapturedDate { get; set; }
                    public Nullable<double> TotalAmount { get; set; }
                    public Nullable<long> IdUserAuthor { get; set; }
                    public Nullable<long> IdSignatureDocument { get; set; }
                    public Nullable<long> IdTransactionState { get; set; }
                    public Nullable<long> IdTransactionOriginal { get; set; }
                    public Nullable<long> IdPayment { get; set; }
        
        public virtual User User { get; set; }
        public virtual TransactionState TransactionState { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Document Document { get; set; }
        public virtual ICollection<ScheduleSetting> ScheduleSettings { get; set; }
        public virtual ICollection<TransactionDue> TransactionDues { get; set; }
        public virtual ICollection<TransactionDue_Transaction> TransactionDue_Transaction { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Transaction Transaction1 { get; set; }
        public virtual Transaction Transaction2 { get; set; }
        public virtual Transaction Transaction11 { get; set; }
        public virtual Transaction Transaction3 { get; set; }
        public virtual ICollection<Transaction_Payment> Transaction_Payment { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual ICollection<Transaction_MailToSend> Transaction_MailToSend { get; set; }
        public virtual ICollection<Transaction_BankStatementStagingDetail> Transaction_BankStatementStagingDetail { get; set; }
        public virtual TransactionAccount TransactionAccount { get; set; }
        public virtual TransactionClass TransactionClass { get; set; }
        public virtual TransactionTemplate TransactionTemplate { get; set; }
    }
    public partial class Transaction_BankStatementStagingDetail
    {
        
            
             public Nullable<long> IdTransaction_BankStatementStagingDetail { get; set; }
                    public Nullable<long> IdTransaction { get; set; }
                    public Nullable<long> IdBankStatementStagingDetail { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual BankStatementStagingDetail BankStatementStagingDetail { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
    public partial class Transaction_MailToSend
    {
        
            
             public Nullable<long> IdTransaction_MailToSend { get; set; }
                    public Nullable<long> IdTransaction { get; set; }
                    public Nullable<long> IdMailToSend { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual MailToSend MailToSend { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
    public partial class Transaction_Payment
    {
        
            
             public Nullable<long> IdTransaction_Payment { get; set; }
                    public Nullable<long> IdTransaction { get; set; }
                    public Nullable<long> IdPayment { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Payment Payment { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
    public partial class TransactionAccount
    {
        public TransactionAccount()
        {
            this.TransactionPresets = new HashSet<TransactionPreset>();
            this.Banks = new HashSet<Bank>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        
            
             public Nullable<long> IdTransactionAccount { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdParentTransactionAccount { get; set; }
                    public Nullable<long> IdTransactionAccountType { get; set; }
                    public Nullable<int> Number { get; set; }
                    public string BankNumber { get; set; }
        
        public virtual ICollection<TransactionPreset> TransactionPresets { get; set; }
        public virtual ICollection<Bank> Banks { get; set; }
        public virtual TransactionAccountType TransactionAccountType { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
    public partial class TransactionAccountType
    {
        public TransactionAccountType()
        {
            this.TransactionAccounts = new HashSet<TransactionAccount>();
        }
    
        
            
             public Nullable<long> IdTransactionAccountType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<TransactionAccount> TransactionAccounts { get; set; }
    }
    public partial class TransactionClass
    {
        public TransactionClass()
        {
            this.TransactionDetailPresets = new HashSet<TransactionDetailPreset>();
            this.TransactionPresets = new HashSet<TransactionPreset>();
            this.TransactionClass1 = new HashSet<TransactionClass>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        
            
             public Nullable<long> IdTransactionClass { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
                    public Nullable<long> IdParentTransactionClass { get; set; }
        
        public virtual ICollection<TransactionDetailPreset> TransactionDetailPresets { get; set; }
        public virtual ICollection<TransactionPreset> TransactionPresets { get; set; }
        public virtual ICollection<TransactionClass> TransactionClass1 { get; set; }
        public virtual TransactionClass TransactionClass2 { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
    public partial class TransactionDetail
    {
        
            
             public Nullable<long> IdTransactionDetail { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdTransaction { get; set; }
                    public Nullable<long> IdProduct { get; set; }
                    public string Description { get; set; }
                    public Nullable<double> Quantity { get; set; }
                    public Nullable<double> Rate { get; set; }
                    public Nullable<long> IdTransactionClass { get; set; }
                    public string Remarks { get; set; }
        
        public virtual Product Product { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual TransactionClass TransactionClass { get; set; }
    }
    public partial class TransactionDetailPreset
    {
        
            
             public Nullable<long> IdTransactionDetailPreset { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdTransactionPreset { get; set; }
                    public Nullable<long> IdProduct { get; set; }
                    public string Description { get; set; }
                    public Nullable<double> Quantity { get; set; }
                    public Nullable<double> Rate { get; set; }
                    public Nullable<long> IdTransactionClass { get; set; }
        
        public virtual Product Product { get; set; }
        public virtual TransactionPreset TransactionPreset { get; set; }
        public virtual TransactionClass TransactionClass { get; set; }
    }
    public partial class TransactionDue
    {
        public TransactionDue()
        {
            this.TransactionDue_Transaction = new HashSet<TransactionDue_Transaction>();
        }
    
        
            
             public Nullable<long> IdTransactionDue { get; set; }
                    public Nullable<long> IdTransaction { get; set; }
                    public Nullable<System.DateTime> DueDate { get; set; }
                    public Nullable<double> AmountDue { get; set; }
                    public Nullable<double> AmountRemaining { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Transaction Transaction { get; set; }
        public virtual ICollection<TransactionDue_Transaction> TransactionDue_Transaction { get; set; }
    }
    public partial class TransactionDue_Transaction
    {
        
            
             public Nullable<long> IdTransactionDue_Transaction { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdTransactionDone { get; set; }
                    public Nullable<long> IdTransactionDue { get; set; }
        
        public virtual TransactionDue TransactionDue { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
    public partial class TransactionPreset
    {
        public TransactionPreset()
        {
            this.BankStatementHitList_TransactionPreset = new HashSet<BankStatementHitList_TransactionPreset>();
            this.BankStatementStagingHit_TransactionPreset = new HashSet<BankStatementStagingHit_TransactionPreset>();
            this.TransactionDetailPresets = new HashSet<TransactionDetailPreset>();
        }
    
        
            
             public Nullable<long> IdTransactionPreset { get; set; }
                    public Nullable<long> IdTransactionType { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdCustomer { get; set; }
                    public Nullable<long> IdTransactionClass { get; set; }
                    public Nullable<long> IdTransactionTemplate { get; set; }
                    public Nullable<long> IdTransactionAccount { get; set; }
                    public Nullable<double> TotalAmount { get; set; }
        
        public virtual ICollection<BankStatementHitList_TransactionPreset> BankStatementHitList_TransactionPreset { get; set; }
        public virtual ICollection<BankStatementStagingHit_TransactionPreset> BankStatementStagingHit_TransactionPreset { get; set; }
        public virtual ICollection<TransactionDetailPreset> TransactionDetailPresets { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TransactionAccount TransactionAccount { get; set; }
        public virtual TransactionClass TransactionClass { get; set; }
        public virtual TransactionTemplate TransactionTemplate { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
    public partial class TransactionState
    {
        public TransactionState()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        
            
             public Nullable<long> IdTransactionState { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
    public partial class TransactionTemplate
    {
        public TransactionTemplate()
        {
            this.TransactionPresets = new HashSet<TransactionPreset>();
            this.Banks = new HashSet<Bank>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        
            
             public Nullable<long> IdTransactionTemplate { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string Description { get; set; }
        
        public virtual ICollection<TransactionPreset> TransactionPresets { get; set; }
        public virtual ICollection<Bank> Banks { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
    public partial class TransactionType
    {
        public TransactionType()
        {
            this.TransactionPresets = new HashSet<TransactionPreset>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        
            
             public Nullable<long> IdTransactionType { get; set; }
                    public string Description { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<TransactionPreset> TransactionPresets { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
    public partial class User
    {
        public User()
        {
            this.BankStatementStagings = new HashSet<BankStatementStaging>();
            this.Orders = new HashSet<Order>();
            this.Payments = new HashSet<Payment>();
            this.Receipts = new HashSet<Receipt>();
            this.RequestType_User = new HashSet<RequestType_User>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        
            
             public Nullable<long> IdUser { get; set; }
                    public string Email { get; set; }
                    public string PasswordHash { get; set; }
                    public string SecurityStamp { get; set; }
                    public string PhoneNumber { get; set; }
                    public bool LockoutEnabled { get; set; }
                    public string UserName { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<long> IdPerson { get; set; }
                    public string FirstName { get; set; }
                    public string LastName { get; set; }
                    public Nullable<bool> NeedPasswordChange { get; set; }
                    public Nullable<bool> EmailConfirmed { get; set; }
                    public Nullable<bool> PhoneNumberConfirmed { get; set; }
                    public Nullable<bool> TwoFactorEnabled { get; set; }
                    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
                    public Nullable<int> AccessFailedCount { get; set; }
        
        public virtual ICollection<BankStatementStaging> BankStatementStagings { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual ICollection<RequestType_User> RequestType_User { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Person Person { get; set; }
    }
    public partial class User_Permission
    {
        
            
             public Nullable<long> IdUser_Permission { get; set; }
                    public Nullable<long> IdUser { get; set; }
                    public Nullable<long> IdPermission { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public Nullable<bool> IsAllowed { get; set; }
        
        public virtual Permission Permission { get; set; }
    }
    public partial class User_Role
    {
        
            
             public Nullable<long> IdUser { get; set; }
            
            
             public Nullable<long> IdRole { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Role Role { get; set; }
    }
    public partial class User_SocialNetwork
    {
        
            
             public Nullable<long> IdUser_SocialNetwork { get; set; }
                    public Nullable<long> IdUser { get; set; }
                    public Nullable<long> IdSocialNetwork { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
                    public string SocialNetworkId { get; set; }
        }
    public partial class Workflow
    {
        public Workflow()
        {
            this.ApprovalMessages = new HashSet<ApprovalMessage>();
            this.RequestTypes = new HashSet<RequestType>();
            this.WorkflowActions = new HashSet<WorkflowAction>();
            this.WorkflowRoles = new HashSet<WorkflowRole>();
            this.WorkflowStates = new HashSet<WorkflowState>();
        }
    
        
            
             public Nullable<long> IdWorkflow { get; set; }
                    public string Description { get; set; }
                    public string WorkflowCode { get; set; }
                    public Nullable<int> DisplayOrder { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<ApprovalMessage> ApprovalMessages { get; set; }
        public virtual ICollection<RequestType> RequestTypes { get; set; }
        public virtual ICollection<WorkflowAction> WorkflowActions { get; set; }
        public virtual ICollection<WorkflowRole> WorkflowRoles { get; set; }
        public virtual ICollection<WorkflowState> WorkflowStates { get; set; }
    }
    public partial class WorkflowAction
    {
        public WorkflowAction()
        {
            this.ApprovalMessages = new HashSet<ApprovalMessage>();
            this.WorkflowTransitions = new HashSet<WorkflowTransition>();
        }
    
        
            
             public Nullable<long> IdWorkflowAction { get; set; }
                    public string Description { get; set; }
                    public string WorkflowActionCode { get; set; }
                    public Nullable<int> DisplayOrder { get; set; }
                    public Nullable<long> IdWorkflow { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<ApprovalMessage> ApprovalMessages { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<WorkflowTransition> WorkflowTransitions { get; set; }
    }
    public partial class WorkflowRole
    {
        public WorkflowRole()
        {
            this.WorkflowTransitions = new HashSet<WorkflowTransition>();
        }
    
        
            
             public Nullable<long> IdWorkflowRole { get; set; }
                    public string Description { get; set; }
                    public string WorkflowRoleCode { get; set; }
                    public Nullable<int> DisplayOrder { get; set; }
                    public Nullable<long> IdWorkflow { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<WorkflowTransition> WorkflowTransitions { get; set; }
    }
    public partial class WorkflowState
    {
        public WorkflowState()
        {
            this.Requests = new HashSet<Request>();
            this.WorkflowTransitions = new HashSet<WorkflowTransition>();
            this.WorkflowTransitions1 = new HashSet<WorkflowTransition>();
        }
    
        
            
             public Nullable<long> IdWorkflowState { get; set; }
                    public string Description { get; set; }
                    public string WorkflowStateCode { get; set; }
                    public Nullable<int> DisplayOrder { get; set; }
                    public Nullable<long> IdWorkflow { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual ICollection<Request> Requests { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<WorkflowTransition> WorkflowTransitions { get; set; }
        public virtual ICollection<WorkflowTransition> WorkflowTransitions1 { get; set; }
    }
    public partial class WorkflowTransition
    {
        public WorkflowTransition()
        {
            this.WorkflowTransitionOnExecutes = new HashSet<WorkflowTransitionOnExecute>();
        }
    
        
            
             public Nullable<long> IdWorkflowTransition { get; set; }
                    public Nullable<long> IdWorkflowStateInitial { get; set; }
                    public Nullable<long> IdWorkflowAction { get; set; }
                    public Nullable<long> IdWorkflowStateFinal { get; set; }
                    public Nullable<long> IdWorkflowRole { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual WorkflowAction WorkflowAction { get; set; }
        public virtual WorkflowRole WorkflowRole { get; set; }
        public virtual WorkflowState WorkflowState { get; set; }
        public virtual WorkflowState WorkflowState1 { get; set; }
        public virtual ICollection<WorkflowTransitionOnExecute> WorkflowTransitionOnExecutes { get; set; }
    }
    public partial class WorkflowTransitionOnExecute
    {
        
            
             public Nullable<long> IdWorkflowTransitionOnExecute { get; set; }
                    public string Action { get; set; }
                    public Nullable<long> IdWorkflowTransition { get; set; }
                    public string JsonContent { get; set; }
                    public Nullable<bool> IsDeactivated { get; set; }
        
        public virtual WorkflowTransition WorkflowTransition { get; set; }
    }
}
